# Generated by Django 3.0.8 on 2020-07-22 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200722_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='path',
        ),
    ]
