# Generated by Django 3.0.8 on 2020-07-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_images_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.RemoveField(
            model_name='images',
            name='size',
        ),
    ]
