# Generated by Django 3.0.8 on 2020-07-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200722_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('descriptor', models.CharField(blank=True, default='no description...', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'db_table': 'Gallery',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
