# Generated by Django 3.0.8 on 2020-07-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20200722_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='head_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/gallery/', verbose_name='Изображение галереи'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='uploads/images/', verbose_name='Загрузить изображение'),
        ),
    ]
