# Generated by Django 3.0.8 on 2020-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20200722_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery'),
        ),
    ]
