# Generated by Django 3.1 on 2021-04-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20210310_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Галерея', 'verbose_name_plural': 'Галереи'},
        ),
    ]
