# Generated by Django 3.1 on 2021-05-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20210422_1112'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table='gallery',
        ),
    ]
