# Generated by Django 3.0.8 on 2020-07-30 15:49

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_auto_20200730_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории документов')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория документов',
                'verbose_name_plural': 'Категории документов',
                'db_table': 'category_documents',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок документа')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок документа')),
                ('text', tinymce.models.HTMLField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.CategoryDocuments', verbose_name='Категория')),
                ('file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
