# Generated by Django 3.1 on 2021-06-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20210310_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydocuments',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.categorydocuments', verbose_name='Родительская категория'),
        ),
    ]
