# Generated by Django 3.1 on 2021-06-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вид занятости',
                'verbose_name_plural': 'Виды занятости',
                'db_table': 'employment',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='vacancies',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='employment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.employment', verbose_name='Вид занятости'),
        ),
    ]
