# Generated by Django 3.1 on 2021-06-11 08:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210611_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='requirements',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Требования'),
        ),
    ]
