# Generated by Django 3.0.8 on 2020-07-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listfiles',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Список файлов', 'verbose_name_plural': 'Списки файлов'},
        ),
    ]
