# Generated by Django 3.0.8 on 2020-07-22 15:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0010_auto_20200722_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название новости')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, null=True, verbose_name='Подзаголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст новости')),
                ('main_image', models.ImageField(upload_to='uploads/images/', verbose_name='Основное изображение')),
                ('original_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на оригинал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
