# Generated by Django 3.0.8 on 2020-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200722_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Основное изображение'),
        ),
    ]
