# Generated by Django 3.0.8 on 2020-08-05 08:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0011_auto_20200722_1602'),
        ('files', '0002_auto_20200730_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории продукции')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок категории')),
                ('descriptor', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
                'db_table': 'category_product',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок продукта')),
                ('descriptor', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('feature', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.CategoryProduct', verbose_name='Категория')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.File', verbose_name='Файл для загрузки')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Images', verbose_name='Основное изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
