# Generated by Django 3.1 on 2020-08-28 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200722_1602'),
        ('product', '0002_auto_20200828_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.images', verbose_name='Основное изображение'),
        ),
    ]
