# Generated by Django 3.1 on 2021-05-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210504_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Категория продукции', 'verbose_name_plural': 'Категории продукции'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
