# Generated by Django 3.1 on 2021-05-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20210310_0950'),
        ('product', '0006_auto_20210504_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='preview_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.images', verbose_name='Изображение'),
        ),
    ]
