# Generated by Django 3.1 on 2021-06-02 05:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_categoryproduct_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='sub_descriptor',
            field=tinymce.models.HTMLField(null=True, verbose_name='Дополнительное описание категории'),
        ),
    ]
