# Generated by Django 3.1 on 2021-06-02 05:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_categoryproduct_sub_descriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='sub_descriptor',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Дополнительное описание категории'),
        ),
    ]
