# Generated by Django 3.1 on 2021-02-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20210215_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='Телефон'),
        ),
    ]
