# Generated by Django 3.1 on 2021-02-15 13:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20210215_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='descriptor',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
    ]
