# Generated by Django 3.1 on 2021-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_auto_20210216_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('descriptor', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('responsible', models.CharField(max_length=256, verbose_name='Ответственный')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('is_phone_visible', models.BooleanField(default=True, verbose_name='Отображение номера телефона')),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='Факс / телефон')),
                ('is_fax_visible', models.BooleanField(default=True, verbose_name='Отображение номера факса')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Электронная почта')),
                ('is_email_visible', models.BooleanField(default=True, verbose_name='Отображение электронной почты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Метод связи',
                'verbose_name_plural': ('Методы связи',),
                'db_table': 'communication_methods',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_email_visible',
            field=models.BooleanField(default=True, verbose_name='Отображение электронной почты'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='is_phone_visible',
            field=models.BooleanField(default=True, verbose_name='Отображение номера телефона'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
