# Generated by Django 3.1 on 2021-03-10 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_auto_20210310_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='communication_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.communicationmethod', verbose_name='Метод связи'),
        ),
    ]
