# Generated by Django 3.1 on 2021-03-10 07:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_personnel_communication_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationmethod',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Метод связи', 'verbose_name_plural': 'Методы связи'},
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='descriptor',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
