# Generated by Django 3.1 on 2021-03-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_auto_20210310_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationmethod',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='communicationmethod',
            name='responsible',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ответственный'),
        ),
    ]
