# Generated by Django 3.1 on 2021-03-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_auto_20210310_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationmethod',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображение данных связи'),
        ),
    ]
