# Generated by Django 3.0.8 on 2020-07-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_image',
        ),
    ]
