# Generated by Django 3.0.8 on 2020-07-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Основное изображение'),
        ),
    ]
