# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_image',
        ),
    ]
