# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20200722_1602'),
        ('article', '0004_remove_article_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Images', verbose_name='Основное изображение'),
        ),
    ]
