# Generated by Django 3.1 on 2020-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на публикацию'),
        ),
    ]
