# Generated by Django 3.1 on 2021-02-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200730_1549'),
        ('publications', '0002_auto_20201007_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.listfiles', verbose_name='Файлы'),
        ),
    ]
