# Generated by Django 3.1 on 2021-02-19 06:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPublication',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('descriptor', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория публикации',
                'verbose_name_plural': 'Категории публикаций',
                'db_table': 'categories_publicatio',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
