# Generated by Django 3.1 on 2021-02-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_categorypublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.categorypublication', verbose_name='Категория'),
        ),
    ]
